---
baseurl: "http://mozaik.rocks/"
title: Mozaïk

canonifyurls: true

permalinks:
  post: /:year/:month/:title/

sitemap:
  changefreq: monthly
  priority:   0.5
  filename:   sitemap.xml

menu:
  main:
    - name:       Use
      identifier: use
      weight:     10

    - name:       Mozaik v1 (stable)
      identifier: use-v1
      URL:        /v1/use/
      parent:     use

    - name:       Mozaik v2 (latest)
      identifier: use-v2
      URL:        /v2/use/
      parent:     use

    - name:       Extend
      identifier: extend
      URL:        /extensions/
      weight:     20

    - name:       Theme
      identifier: themes
      URL:        /themes/
      weight:     30

    - name:       Hack
      identifier: hack
      weight:     40

    - name:       Mozaik v1 (stable)
      identifier: hack-v1
      URL:        /v1/hack/
      parent:     hack

    #- name:       Mozaik v2 (latest)
    #  identifier: hack-v2
    #  URL:        /v2/hack/
    #  parent:     hack

    - name:       News
      identifier: news
      URL:        /news/
      weight:     50

params:
  AuthorName: "Raphaël Benitte"
  GitHubUser: "plouc"

  mozaikVersions:       [1, 2]
  mozaikCurrentVersion: 1

  references:
    - image: refs/jolicode.svg
      link:  http://jolicode.com/
      label: JoliCode

    - image: refs/canalplus.png
      link:  http://canalplus.github.io/
      label: Canal+

    - image: refs/aptus-health.png
      link:  http://www.aptushealth.com/
      label: Aptus Health

    - image: refs/sc5.png
      link:  https://sc5.io/
      label: SC5

  useCases:
    - title: Mozaïk meets Apache Spark, Rock-Paper-Scissors!
      link:  https://developer.ibm.com/clouddataservices/2015/12/01/humans-vs-apache-spark-building-our-rock-paper-scissors-game/

    - title: JoliDashboard at Jolicode, serious geeks having fun with Mozaïk
      link:  http://jolicode.com/blog/joliday-2015-avec-de-la-sciure-de-l-etain-et-des-lego

    - title: Six Open Source Dashboards to Organize Your Data
      link:  http://www.astronomer.io/blog/six-open-source-dashboards

  themes:
    - name:       night-blue
      screenshot: night-blue.png

    - name:       bordeau
      screenshot: bordeau.png

    - name:       light-grey
      screenshot: light-grey.png

    - name:       yellow
      screenshot: yellow.png

    - name:       light-yellow
      screenshot: light-yellow.png

  features:
    - title:        Scalable layout
      illustration: mozaik-icon-extendable.png
      description: |
        **Mozaïk** dashboards support multiple devices through adaptive layout.
        You can either put your dashboard on a big screen in the open space, or consult it on your smartphone.

    - title:        Themes support
      illustration: mozaik-icon-themes.png
      link:         /themes/
      description: |
        **Mozaïk** dashboard comes with 6 themes and makes it easy to develop your own theme.

    - title:        Extendable by modules
      illustration: mozaik-icon-extendable.png
      link:         /extensions/
      description: |
        **Mozaïk** widgets are maintained as separate modules, thus available via mozaik-ext-&lt;name&gt; in npm.js.

    - title:        Grid positioning
      illustration: mozaik-icon-positioning.png
      link:         /v1/use/grid/
      description: |
        **Mozaïk** provides a simple way to define your dashboard layout using a grid system.

    - title:        Optimized backend communication
      illustration: mozaik-icon-backend.png
      link:         /v1/hack/client/
      description: |
        Most extensions need to communicate with APIs. **Mozaïk** eases this by providing a backend, which handles API calls and pushes data to widgets through websockets.

    - title:        Multi dashboards
      illustration: mozaik-icon-extendable.png
      description: |
        Sometimes, a single dashboard is not enough. **Mozaïk** allows multiple dashboards with a smooth transition.

  extensions:
    - name:        mozaik-ext-github
      description: Github widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-github
      demo:        https://mozaik-github.herokuapp.com/
      travis:      plouc/mozaik-ext-github
      compat:      [1, 2]
      tags:
        - github

    - name:        mozaik-ext-gitlab
      description: GitLab widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-gitlab
      demo:        https://mozaik-gitlab.herokuapp.com/
      travis:      plouc/mozaik-ext-gitlab
      compat:      [1, 2]
      tags:
        - gitlab

    - name:        mozaik-ext-slack
      description: Slack widgets for Mozaïk.
      link:        https://github.com/juhamust/mozaik-ext-slack
      compat:      [1]
      tags:
        - slack

    - name:        mozaik-ext-travis
      description: Travis widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-travis
      demo:        https://mozaik-travis.herokuapp.com/
      travis:      plouc/mozaik-ext-travis
      compat:      [1, 2]
      tags:
        - travis
        - ci
        - testing

    - name:        mozaik-ext-time
      description: Time widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-time
      demo:        https://mozaik-time.herokuapp.com/
      travis:      plouc/mozaik-ext-time
      compat:      [1, 2]
      tags:
        - time

    - name:        mozaik-ext-weather
      description: Weather widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-weather
      travis:      plouc/mozaik-ext-weather
      compat:      [1]
      tags:
        - weather

    - name:        mozaik-ext-jenkins
      description: Jenkins widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-jenkins
      travis:      plouc/mozaik-ext-jenkins
      compat:      [1]
      tags:
        - jenkins
        - ci
        - testing

    - name:        mozaik-ext-teamcity
      description: Teamcity widgets for Mozaïk.
      link:        https://github.com/gazab/mozaik-ext-teamcity
      compat:      [1]
      tags:
        - teamcity
        - ci

    - name:        mozaik-ext-heroku
      description: Heroku widgets for Mozaïk.
      link:        https://github.com/plouc/mozaik-ext-heroku
      travis:      plouc/mozaik-ext-heroku
      compat:      [1]
      tags:
        - heroku
        - deploy

    - name:        mozaik-ext-analytics
      description: Google analytics widgets for Mozaïk.
      link:        https://github.com/SC5/mozaik-ext-analytics
      compat:      [1]
      tags:
        - google
        - analytics

    - name:        mozaik-ext-switch
      description: Multiple widgets with periodic switching.
      link:        https://github.com/juhamust/mozaik-ext-switch
      compat:      [1]
      tags:
        - switch

    - name:        mozaik-ext-embed
      description: Mozaïk extension to embed raw content like HTML markup into widget.
      link:        https://github.com/juhamust/mozaik-ext-embed
      compat:      [1]
      tags:
        - iframe
        - html

    - name:        mozaik-ext-iframe
      description: iFrame widgets for Mozaïk.
      link:        https://github.com/tomav/mozaik-ext-iframe
      compat:      [1]
      tags:
        - iframe

    - name:        mozaik-ext-calendar
      description: Google calendar widgets for Mozaïk.
      link:        https://github.com/SC5/mozaik-ext-analytics
      compat:      [1]
      tags:
        - google
        - calendar

    - name:        mozaik-ext-json
      description: Mozaïk extension that displays a distant JSON object in a widget.
      link:        https://github.com/jtbonhomme/mozaik-ext-json
      compat:      [1]
      tags:
        - json

    - name:        mozaik-ext-multijson
      description: Widget to display information from multiple json sources.
      link:        https://github.com/jtbonhomme/mozaik-ext-multijson
      compat:      [1]
      tags:
        - json

    - name:        mozaik-ext-value
      description: Mozaïk value plugin.
      link:        https://github.com/arildwtv/mozaik-ext-value
      compat:      [1]
      tags:
        - basic
        - value

    - name:        mozaik-ext-bamboo
      description: Bamboo widgets for Mozaïk.
      link:        https://github.com/swissmanu/mozaik-ext-bamboo
      compat:      [1]
      tags:
        - bamboo

    - name:        mozaik-ext-image
      description: Show image in a Mozaïk widget.
      link:        https://www.npmjs.com/package/mozaik-ext-image
      compat:      [1]
      tags:
        - basic
        - image

    - name:        mozaik-ext-okrs
      description: Show OKR week trends from Google Sheets.
      link:        https://github.com/grahamar/mozaik-ext-okrs
      compat:      [1]
      tags:
        - google
        - spreadsheet
        - OKR

    - name:        mozaik-ext-saucelabs
      description: SauceLabs widgets for Mozaïk.
      link:        https://github.com/iamfiscus/mozaik-ext-saucelabs
      compat:      [1]
      tags:
        - saucelabs
        - ci
        - testing

...